spring.application.name=product-service

# ==========================================
# Server
# ==========================================

server.port=${PORT:8082}


# ==========================================
# PostgreSQL Configuration
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always


# ==========================================
# Redis
# ==========================================

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.type=redis


# ==========================================
# Logging
# ==========================================

logging.level.org.springframework.cache=DEBUG
